- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    - name: "Install, start and enable httpd"
      shell:
        cmd: |
          yum install httpd
          systemctl start httpd
          systemctl enable httpd