- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  tasks:
    - name: "Install, start and enable httpd"
      shell:
        cmd: |
          yum install httpd;
          systemctl start httpd;
          systemctl enable httpd;